name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run backend
        run: uvicorn backend.main:app --port 8000 --reload
